import Head from "next/head";
import Banner from "../components/Home/Banner";
import HomeMenu from "../components/HomeMenu";

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Audiophile</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Banner />
      <main className='w-full max-w-[1190px] px-6 md:px-10 lg:mx-auto'>
        <div className='mt-[92px] md:mt-[148px] lg:mt-[200px]'>
          <HomeMenu />
        </div>

        {/* <div className='relative mt-[96px] h-[720px] rounded-lg bg-orange'>
          <svg
            width='944'
            height='944'
            xmlns='http://www.w3.org/2000/svg'
            className='mx-auto max-h-[944px] max-w-[944px]'
          >
            <g stroke='#FFF' fill='none' fillRule='evenodd' opacity='.202'>
              <circle cx='472' cy='472' r='235.5' />
              <circle cx='472' cy='472' r='270.5' />
              <circle cx='472' cy='472' r='471.5' />
            </g>
          </svg>
        </div> */}
      </main>
    </div>
  );
}
